import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from "typeorm"

/**
 * TypeORM entity representing a successfully crawled page stored in Postgres.
 * The unique constraint on `url` enables UPSERT semantics — re-seeding a URL
 * updates the existing row instead of inserting a duplicate.
 *
 * Schema authority: `init.sql` (mounted into Postgres at startup via compose.yaml).
 * `synchronize: false` is set in AppModule so TypeORM never silently alters the schema.
 */
@Entity({ name: "page" })
export class Page {
    /** UUID primary key generated by Postgres gen_random_uuid(). */
    @PrimaryGeneratedColumn("uuid")
    id!: string

    /** Absolute URL of the crawled page; unique so UPSERT works correctly. */
    @Column({ type: "varchar", unique: true })
    url!: string

    /**
     * Hostname extracted from the URL.
     * Used as the key for politeness state in Redis (crawler:host:<host>:lastFetched).
     */
    @Column({ type: "varchar" })
    host!: string

    /** Raw HTML body returned by the fake-internet fixture. */
    @Column({ name: "html_body", type: "text" })
    htmlBody!: string

    /** MIME content type returned by the fake-internet fixture (e.g. text/html). */
    @Column({ name: "content_type", type: "varchar" })
    contentType!: string

    /** HTTP status code returned by the fake-internet fixture. */
    @Column({ name: "status_code", type: "int" })
    statusCode!: number

    /** Timestamp set at row creation/update; used for ORDER BY fetchedAt DESC. */
    @CreateDateColumn({ name: "fetched_at", type: "timestamptz" })
    fetchedAt!: Date
}
